version: 0.0.0.{build}
skip_tags: true
image: Visual Studio 2017
clone_folder: c:\projects\dev-marketplace
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
before_build:
- ps: dotnet restore
- npm install src\UI\
- npm install gulp -g
- ps: Push-Location ".\src\UI\"; npm install gulp; gulp -b ".\" --color --gulpfile "Gulpfile.js" copy-all; Pop-Location;
build:
  verbosity: minimal
notifications:
- provider: Email
  to:
  - cracker4o@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
  
