//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountContent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal AccountContent() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Localization.AccountContent", typeof(AccountContent).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Thank you for registering with DevMarketplace. Please activate your account by clicking on the following link: &lt;a class=&quot;btn&quot; href=&quot;{0}&quot;&gt;Activate&lt;/a&gt;.
        /// </summary>
        public static string ActivationEmailBodyText {
            get {
                return ResourceManager.GetString("ActivationEmailBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Activate your DevMarketplace account.
        /// </summary>
        public static string ActivationEmailSubject {
            get {
                return ResourceManager.GetString("ActivationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} you should receive your account activation e-mail in a moment. Please check your e-mail at {1} and click on the activation link..
        /// </summary>
        public static string ActivationGuideText {
            get {
                return ResourceManager.GetString("ActivationGuideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dear {0},.
        /// </summary>
        public static string AddressUserByNameText {
            get {
                return ResourceManager.GetString("AddressUserByNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Company.
        /// </summary>
        public static string CompanyText {
            get {
                return ResourceManager.GetString("CompanyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Create an account.
        /// </summary>
        public static string CreateAnAccountText {
            get {
                return ResourceManager.GetString("CreateAnAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The DevMarketplace team.
        /// </summary>
        public static string DevMarketplaceTeamText {
            get {
                return ResourceManager.GetString("DevMarketplaceTeamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You must have a confirmed email to log in..
        /// </summary>
        public static string EmailConfirmationRequiredErrorText {
            get {
                return ResourceManager.GetString("EmailConfirmationRequiredErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstNameText {
            get {
                return ResourceManager.GetString("FirstNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Forgotten password?.
        /// </summary>
        public static string ForgottenPasswordText {
            get {
                return ResourceManager.GetString("ForgottenPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid login attempt.
        /// </summary>
        public static string InvalidLoginAttemptText {
            get {
                return ResourceManager.GetString("InvalidLoginAttemptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid username/password combination.
        /// </summary>
        public static string InvalidUsernameErrorText {
            get {
                return ResourceManager.GetString("InvalidUsernameErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastNameText {
            get {
                return ResourceManager.GetString("LastNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPasswordText {
            get {
                return ResourceManager.GetString("NewPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The password doesn&apos;t match the password confirmation.
        /// </summary>
        public static string PasswordDoesNotMatchError {
            get {
                return ResourceManager.GetString("PasswordDoesNotMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The password must be at least 8 characters long.
        /// </summary>
        public static string PasswordLengthRequirementText {
            get {
                return ResourceManager.GetString("PasswordLengthRequirementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The password must be at least 8 characters and must contain 1 lowercase character, 1 uppercase character and a number.
        /// </summary>
        public static string PasswordRequirementsText {
            get {
                return ResourceManager.GetString("PasswordRequirementsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterText {
            get {
                return ResourceManager.GetString("RegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Registration Complete.
        /// </summary>
        public static string RegistrationCompleteText {
            get {
                return ResourceManager.GetString("RegistrationCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Create an account.
        /// </summary>
        public static string RegistrationPageTitle {
            get {
                return ResourceManager.GetString("RegistrationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Repeat Password.
        /// </summary>
        public static string RepeatPasswordText {
            get {
                return ResourceManager.GetString("RepeatPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An e-mail with a reset link was sent to {0}.
        /// </summary>
        public static string ResetLinkEmailText {
            get {
                return ResourceManager.GetString("ResetLinkEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please reset your password by clicking on this link: &lt;a class=&quot;btn&quot; href=&quot;{0}&quot;&gt;Reset Password&lt;/a&gt;.
        /// </summary>
        public static string ResetPasswordEmailBodyText {
            get {
                return ResourceManager.GetString("ResetPasswordEmailBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Reset your DevMarketplace password.
        /// </summary>
        public static string ResetPasswordEmailSubjectText {
            get {
                return ResourceManager.GetString("ResetPasswordEmailSubjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPasswordText {
            get {
                return ResourceManager.GetString("ResetPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignInText {
            get {
                return ResourceManager.GetString("SignInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOutText {
            get {
                return ResourceManager.GetString("SignOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Success.
        /// </summary>
        public static string SuccessText {
            get {
                return ResourceManager.GetString("SuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Profile.
        /// </summary>
        public static string UserProfilePageTitle {
            get {
                return ResourceManager.GetString("UserProfilePageTitle", resourceCulture);
            }
        }
    }
}
