//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LayoutContent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal LayoutContent() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Localization.LayoutContent", typeof(LayoutContent).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Find a project....
        /// </summary>
        public static string FindAProjectText {
            get {
                return ResourceManager.GetString("FindAProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogInMenuText {
            get {
                return ResourceManager.GetString("LogInMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchButtonText {
            get {
                return ResourceManager.GetString("SearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUpMenuText {
            get {
                return ResourceManager.GetString("SignUpMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Developer marketplace.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Developer Marketplace.
        /// </summary>
        public static string SiteTitleText {
            get {
                return ResourceManager.GetString("SiteTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Start a project.
        /// </summary>
        public static string StartAProjectMenuText {
            get {
                return ResourceManager.GetString("StartAProjectMenuText", resourceCulture);
            }
        }
    }
}
