//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrganizationContent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal OrganizationContent() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Localization.OrganizationContent", typeof(OrganizationContent).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Company.
        /// </summary>
        public static string CompanyText {
            get {
                return ResourceManager.GetString("CompanyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Country.
        /// </summary>
        public static string CountryText {
            get {
                return ResourceManager.GetString("CountryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateButtonText {
            get {
                return ResourceManager.GetString("CreateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Create organization.
        /// </summary>
        public static string CreateOrganizationTitle {
            get {
                return ResourceManager.GetString("CreateOrganizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Location (City, State ...).
        /// </summary>
        public static string LocationText {
            get {
                return ResourceManager.GetString("LocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Organization bio.
        /// </summary>
        public static string OrganizationDescription {
            get {
                return ResourceManager.GetString("OrganizationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Organization e-mail.
        /// </summary>
        public static string OrganizationEmailText {
            get {
                return ResourceManager.GetString("OrganizationEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Organization name.
        /// </summary>
        public static string OrganizationNameText {
            get {
                return ResourceManager.GetString("OrganizationNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Organization.
        /// </summary>
        public static string OrganizationText {
            get {
                return ResourceManager.GetString("OrganizationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Team.
        /// </summary>
        public static string TeamText {
            get {
                return ResourceManager.GetString("TeamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Web site.
        /// </summary>
        public static string WebSiteText {
            get {
                return ResourceManager.GetString("WebSiteText", resourceCulture);
            }
        }
    }
}
